	CREATE DATABASE IF NOT EXISTS PRUEBAANGULAR;
	USE PRUEBAANGULAR;
	CREATE TABLE IF NOT EXISTS usuario(
		id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	   nombres VARCHAR(30),
		apellidos VARCHAR(30),
	   cedula VARCHAR(30) UNIQUE,
	   correo VARCHAR(30) UNIQUE,
	   telefono VARCHAR(30)
	) ;